name: cardio
channels:
  - conda-forge
dependencies:
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.5.18.1
  - certifi=2022.5.18.1
  - click=8.1.3
  - cycler=0.11.0
  - dash=2.4.1
  - dash-bootstrap-components=1.1.0
  - dash-extensions=0.0.71
  - editorconfig=0.12.3
  - flask=2.1.2
  - flask-caching=1.10.1
  - flask-compress=1.12
  - fonttools=4.33.3
  - freetype=2.10.4
  - giflib=5.2.1
  - importlib-metadata=4.11.4
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - jsbeautifier=1.14.0
  - kiwisolver=1.4.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  #- libcxx=14.0.4
  - libdeflate=1.10
  - libffi=3.4.2
  #- libgfortran=5.0.0.dev0
  #- libgfortran5=11.0.1.dev0
  - liblapack=3.9.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libtiff=4.4.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - more-itertools=8.13.0
  - munkres=1.1.4
  - ncurses=6.3
  - numpy=1.22.4
  - openjpeg=2.4.0
  - openssl=3.0.3
  - packaging=21.3
  - pandas=1.4.2
  - pillow=9.1.1
  - pip=22.1.2
  - plotly=5.8.0
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.1
  - readline=8.1
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - setuptools=62.3.2
  - six=1.16.0
  - sqlite=3.38.5
  - tenacity=8.0.1
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tornado=6.1
  - tzdata=2022a
  - unicodedata2=14.0.0
  - werkzeug=2.1.2
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip
  - pip:
      - uszipcode